import os
import private

SECRET_KEY = private.SECRET_KEY
SQLALCHEMY_DATABASE_URI = 'postgresql://localhost/db'
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get("SQLALCHEMY_TRACK_MODIFICATIONS", True)

STARTING_ADMIN1 = private.STARTING_ADMIN1
STARTING_ADMIN_PASS = private.STARTING_ADMIN_PASS

SECURITY_PASSWORD_HASH = private.SECURITY_PASSWORD_HASH
SECURITY_PASSWORD_SALT = private.SECURITY_PASSWORD_SALT

# controls what page you see after login
SECURITY_POST_LOGIN_VIEW = '/display' 

SECURITY_REGISTERABLE = os.environ.get("SECURITY_REGISTERABLE", True)
SECURITY_CONFIRMABLE = os.environ.get("SECURITY_CONFIRMABLE", True)
SECURITY_RECOVERABLE = os.environ.get("SECURITY_RECOVERABLE", True)